/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class bookManager extends javax.swing.JFrame {

    Connection conn=null;
      PreparedStatement pst=null;
    ResultSet rs=null;
    
    public bookManager() {
        initComponents();
        conn=mysqlconnection.connectDB();
        showTable();
    }
    
    
    public void showTable(){
        
        try{
        String sql="select *from book";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        book_table.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception e){
            
        }
        
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        book_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        edit_table_data = new javax.swing.JButton();
        delete_book = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        serial_delete = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        j7 = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        book_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                book_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(book_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 100));

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 110, 30));

        edit_table_data.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        edit_table_data.setText("Update");
        edit_table_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_table_dataActionPerformed(evt);
            }
        });
        getContentPane().add(edit_table_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 110, 30));

        delete_book.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        delete_book.setText("Delete");
        delete_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bookActionPerformed(evt);
            }
        });
        getContentPane().add(delete_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 110, 30));

        jButton5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 110, 30));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, 30));
        getContentPane().add(serial_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 70, 30));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 30));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 30));
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 30));
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 30));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 30));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Row");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 60, 30));
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 130, 30));
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, 30));
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 130, 30));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Column");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 60, 30));
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 130, 30));

        refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/back.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       addNewBook h7=new addNewBook();
       h7.setVisible(true);
       this.hide();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    private void delete_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bookActionPerformed
        String sql="delete from book where bserial =?";
        try{
            String h=serial_delete.getText();
            pst=conn.prepareStatement(sql);
            
            pst.setString(1,h);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        showTable();
    }//GEN-LAST:event_delete_bookActionPerformed

    private void edit_table_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_table_dataActionPerformed

        
        try{
              int row = book_table.getSelectedRow();
            String Table_click =(book_table.getModel().getValueAt(row, 0).toString());
            
         String v1=serial_delete.getText();
          String v2=j1.getText();
          String v3=j2.getText();
          String v4=j3.getText();
          String v5=j4.getText();
          String v6=j5.getText();
          String v7=j7.getText();
          
          String sql="update book set bserial='"+v1+"' , bname='"+v2+"' ,bauthor='"+v3+"',bedition='"+v4+"',bcolumn='"+v5+"',brow='"+v6+"',amount='"+v7+"' where bserial='"+v1+"' ";
         pst=conn.prepareStatement(sql);
         pst.execute();
         JOptionPane.showMessageDialog(null,"Data updated"); 
         
         
         
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,e); 
     }
     showTable();   
        
    }//GEN-LAST:event_edit_table_dataActionPerformed

    
    
    private void book_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_tableMouseClicked
    
        try{
            int row=book_table.getSelectedRow();
            String Table_click=(book_table.getModel().getValueAt(row,0).toString());
            String sql="select * from book where bserial=' "  +Table_click+" '";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("bserial");
                serial_delete.setText(add1);
                
                
                
                String add2=rs.getString("bname");
               j1.setText(add2);
               
                String add3=rs.getString("bauthor");
               j2.setText(add3);
                 
               String add4=rs.getString("bedition");
              j3.setText(add4);
                 
              String add5=rs.getString("brow");
                j4.setText(add5);
                
                 String add6=rs.getString("bcolumn");
               j5.setText(add6);
                  
               String add7=rs.getString("amount");
               j7.setText(add7);
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_book_tableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Manager n7=new Manager();
       n7.setVisible(true);
       this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        
        serial_delete.setText("");
         j1.setText("");
          j2.setText("");
            j3.setText("");
          j4.setText("");
            j5.setText("");
          j7.setText("");
        
        
        
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable book_table;
    private javax.swing.JButton delete_book;
    private javax.swing.JButton edit_table_data;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField serial_delete;
    // End of variables declaration//GEN-END:variables
}
