/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        manageBook = new javax.swing.JButton();
        borrowjlebel1 = new javax.swing.JLabel();
        addNewStudent1 = new javax.swing.JButton();
        bookjlebel2 = new javax.swing.JLabel();
        borroBook1 = new javax.swing.JButton();
        borrowjlebel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/Home-64.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 130, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Manage Member");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 20));

        manageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/booksmanage.png"))); // NOI18N
        manageBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookActionPerformed(evt);
            }
        });
        getContentPane().add(manageBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, 90));

        borrowjlebel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrowjlebel1.setForeground(new java.awt.Color(255, 255, 204));
        borrowjlebel1.setText("Home");
        getContentPane().add(borrowjlebel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 50, 20));

        addNewStudent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/new user.png"))); // NOI18N
        addNewStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudent1ActionPerformed(evt);
            }
        });
        getContentPane().add(addNewStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 90));

        bookjlebel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookjlebel2.setForeground(new java.awt.Color(255, 255, 204));
        bookjlebel2.setText("Book Management");
        getContentPane().add(bookjlebel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 140, 20));

        borroBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/Borrow Book-50.png"))); // NOI18N
        borroBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borroBook1ActionPerformed(evt);
            }
        });
        getContentPane().add(borroBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 140, 90));

        borrowjlebel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrowjlebel2.setForeground(new java.awt.Color(255, 255, 204));
        borrowjlebel2.setText("Manage Borrower");
        getContentPane().add(borrowjlebel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 140, 20));

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("WELCOME to");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setText("Kamp Lintfort Bibliothek");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 450, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/back.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

signIn s=new signIn();
s.setVisible(true);
this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void addNewStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudent1ActionPerformed
studentManagement sm7=new studentManagement();
sm7.setVisible(true);
this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewStudent1ActionPerformed

    private void borroBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borroBook1ActionPerformed
      borro_book bmw=new borro_book();
      bmw.setVisible(true);
      this.hide();
        
        
    }//GEN-LAST:event_borroBook1ActionPerformed

    private void manageBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookActionPerformed
      bookManager bm=new bookManager();
      bm.setVisible(true);
      this.hide();
    }//GEN-LAST:event_manageBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewStudent1;
    private javax.swing.JLabel bookjlebel2;
    private javax.swing.JButton borroBook1;
    private javax.swing.JLabel borrowjlebel1;
    private javax.swing.JLabel borrowjlebel2;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton manageBook;
    // End of variables declaration//GEN-END:variables

  
}
