
package project;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class studentManagement extends javax.swing.JFrame {
    Connection conn=null;
      PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    public studentManagement() {
        initComponents();
      conn=mysqlconnection.connectDB();
      showStable();
    }

    public void showStable(){
        
         try{
        String sql="select *from student_data";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        sTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception e){
            
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteStudent = new javax.swing.JButton();
        add_new_student = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        k2 = new javax.swing.JTextField();
        editStudent1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        k1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        k3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        k4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        k5 = new javax.swing.JTextField();
        refreshbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteStudent.setText("DELETE");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });
        getContentPane().add(deleteStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 80, 30));

        add_new_student.setText("Register");
        add_new_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_studentActionPerformed(evt);
            }
        });
        getContentPane().add(add_new_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 30));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cont");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, 20));
        getContentPane().add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));

        editStudent1.setText("Update");
        editStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudent1ActionPerformed(evt);
            }
        });
        getContentPane().add(editStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 80, 30));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 70, 30));

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 80, 30));

        sTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 150));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, 20));
        getContentPane().add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, 30));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));
        getContentPane().add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 90, 30));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, 20));
        getContentPane().add(k4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, 30));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("dept");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 60, 20));
        getContentPane().add(k5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 100, 30));

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo/back.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Manager mb=new Manager();
        mb.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        decision sn=new decision();
        sn.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_new_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_studentActionPerformed
        addStudent as=new addStudent();
as.setVisible(true);
this.hide();
    }//GEN-LAST:event_add_new_studentActionPerformed

    private void sTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sTableMouseClicked
try{
    
    int row=sTable.getSelectedRow();
String table_click=(sTable.getModel().getValueAt(row,0).toString());    

   String sql="select * from student_data where name='"+table_click+"'";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    
    if(rs.next()){
        String h1=rs.getString("name");
        k1.setText(h1);
        String h2=rs.getString("id");
        k2.setText(h2);
         String h3=rs.getString("dept");
        k3.setText(h3);
         String h4=rs.getString("contact");
        k4.setText(h4);
         String h5=rs.getString("password");
        k5.setText(h5);
    }
    
    
}   catch(Exception e){
        
    }   
       
        
        
        
          
    }//GEN-LAST:event_sTableMouseClicked

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
       String sql="delete from student_data where id =?";
        try{
            String h1=k2.getText();
            pst=conn.prepareStatement(sql);
            
            pst.setString(1,h1);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        showStable();
        
        
        
        
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void editStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudent1ActionPerformed
  
        
         try{
              int row = sTable.getSelectedRow();
            String table_click =(sTable.getModel().getValueAt(row, 0).toString());
            
         String u1=k1.getText();
          String u2=k2.getText();
          String u3=k3.getText();
          String u4=k4.getText();
          String u5=k5.getText();
          
          
          String sql="update student_data set name='"+u1+"' , id='"+u2+"' ,dept='"+u3+"',contact='"+u4+"',password='"+u5+"' where id='"+u2+"' ";
         pst=conn.prepareStatement(sql);
         pst.execute();
         JOptionPane.showMessageDialog(null,"Data updated"); 
         
         
         
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,e); 
     }
     showStable();   
        
        
    }//GEN-LAST:event_editStudent1ActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        
        k1.setText("");
        k2.setText("");
        k3.setText("");
        k4.setText("");
        k5.setText("");
        //k1.setText("");
        
    }//GEN-LAST:event_refreshbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_student;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JButton editStudent1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField k1;
    private javax.swing.JTextField k2;
    private javax.swing.JTextField k3;
    private javax.swing.JTextField k4;
    private javax.swing.JTextField k5;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTable sTable;
    // End of variables declaration//GEN-END:variables
}
